import { Link } from 'react-router-dom';
import { Home, Mail, MapPin, Phone } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="mt-20 border-t border-slate-200 bg-white">
      <div className="container-page grid gap-10 py-12 md:grid-cols-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="rounded-xl bg-brand-600 p-1.5 text-white"><Home className="h-5 w-5" /></span>
            <span className="text-lg font-extrabold text-ink-900">RentEase AI</span>
          </div>
          <p className="mt-3 max-w-xs text-sm text-ink-500">
            Find a place that feels like home. PGs, rooms and rentals matched to your budget, location and lifestyle.
          </p>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-ink-900">Explore</h3>
          <ul className="mt-3 space-y-2 text-sm text-ink-500">
            <li><Link to="/properties" className="hover:text-brand-700">All properties</Link></li>
            <li><Link to="/recommendations" className="hover:text-brand-700">Smart recommendations</Link></li>
            <li><Link to="/compare" className="hover:text-brand-700">Compare properties</Link></li>
            <li><Link to="/favourites" className="hover:text-brand-700">Saved places</Link></li>
          </ul>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-ink-900">For owners</h3>
          <ul className="mt-3 space-y-2 text-sm text-ink-500">
            <li><Link to="/owner/properties/new" className="hover:text-brand-700">List your property</Link></li>
            <li><Link to="/owner" className="hover:text-brand-700">Owner dashboard</Link></li>
            <li><Link to="/owner/inquiries" className="hover:text-brand-700">Tenant inquiries</Link></li>
            <li><Link to="/about" className="hover:text-brand-700">How it works</Link></li>
          </ul>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-ink-900">Reach us</h3>
          <ul className="mt-3 space-y-2 text-sm text-ink-500">
            <li className="flex items-center gap-2"><Mail className="h-4 w-4" /> hello@rentease.ai</li>
            <li className="flex items-center gap-2"><Phone className="h-4 w-4" /> +91 98100 00000</li>
            <li className="flex items-center gap-2"><MapPin className="h-4 w-4" /> New Delhi, India</li>
          </ul>
        </div>
      </div>

      <div className="border-t border-slate-200 py-5">
        <p className="container-page text-center text-xs text-ink-500">
          RentEase AI - built as a B.Tech minor project. Recommendations are generated by a transparent
          preference matching engine, not a trained ML model.
        </p>
      </div>
    </footer>
  );
}
